# Sync any changes to this *other than where explicitly specified* with the copy
# in `nostarch/book.toml`!

[book]
title = "The Rust Programming Language"
authors = ["Steve Klabnik", "Carol Nichols", "Contributions from the Rust Community"]

[output.html]
additional-css = [
  "ferris.css",
  "theme/semantic-notes.css", 
  "theme/listing.css",
  "theme/2018-edition.css",
  "js-extensions/packages/feedback/dist/index.css",  
]
additional-js = [
  "ferris.js",
  "js-extensions/packages/telemetry/dist/index.js",
  "js-extensions/packages/feedback/dist/index.js",
]

git-repository-url = "https://github.com/cognitive-engineering-lab/rust-book"

[preprocessor.quiz]
fullscreen = true
validate = true
cache-answers = true
more-words = "words.dic"

[preprocessor.aquascope]

# [build]
# extra-watch-dirs = ["quizzes", "../mdbook-quiz/target/debug", "js-extensions/packages/feedback/dist"]

# Do not sync this preprocessor; it is for the HTML renderer only.
[preprocessor.trpl-note]

[preprocessor.trpl-listing]
output-mode = "default"

# [output.linkcheck]

[rust]
edition = "2021"